### ISSUE TITLE
[FEATURE] Activation required only for specific customer groups

### ISSUE THREAD

**Issue by Vinai** [Vinai/customer-activation#11]
This feature might be useful if a site lets customer select if they are resellers or general customers during registration.
The setting of the customer group will not be part of the customer activation module, only the activation.

**Comment by J-dsgn** [comment]
Hi,

In my Mage shop is for a certain customer group set: Activation required, by selecting this group at Customer Groups section in backend.

See screenshot:

https://snag.gy/CW8JBl.jpg

But in frontend when customer group registrates it is directly active without required activation by administrator ?!?!

See screenshot:

https://snag.gy/UwM8Au.jpg

While in magento backend section: Manage customers, this customer group registration has status Customer Activated: No ?!?!

See screenshot:

https://snag.gy/tfCiy8.jpg

**QUESTION**

How to set extension right or solve this bug so customer group registration is in frontend after registration default: not active, and requires activation by administrator?

Best regards,

Joris
