### ISSUE TITLE
Mark this extension as unsupported

### ISSUE THREAD

**Issue by andrewhowdencom** [Vinai/customer-activation#126]
Currently there is a problem in which none of the existing maintainers have the appropriate time to continue to improve this extension.

While it would be ideal to give someone else the extension to continue to maintain, practically speaking GitHub already has mechanisms to indicate both that:

1. The extension is no longer maintained (https://help.github.com/en/articles/archiving-a-github-repository)
2. The extension is open to maintenance by others (OSL License & GitHubs Fork feature)

Archiving an extension does not change one's ability to access the repository, rather only making it read only. For example,

https://github.com/littlemanco/wiki--deprecated

As an alternative, it would be possible to automatically respond to issue with a bot like:

https://github.com/probot/autoresponder

However, the simplest mechanism here is simply to archive it. It can be unarchived in future as required.

**Comment by Vinai** [comment]
I've added a H1 header to the readme of all my Magento 1 extensions.

**Comment by Vinai** [comment]
Oh, I don't think archiving is a good option, I believe publicly published code should never be removed.
