### ISSUE TITLE
Fatal Error on Manage Customers Page

### ISSUE THREAD

**Issue by codemecurtis** [Vinai/customer-activation#20]
I select the customer select customer activated from the drop-down and then select yes after clicking submit I get this:

Fatal error: Call to a member function getBackend() on a non-object in /home/techey5/public_html/opticsinstock.com/app/code/community/Netzarbeiter/CustomerActivation/Model/Resource/Customer.php on line 45

Thank You,

**Comment by Ashton1986** [comment]
Thank you so much! I've nearly hung me because of this issue, but now it's solved.
