### ISSUE TITLE
Customer Activation module not working.

### ISSUE THREAD

**Issue by kisadam220** [Vinai/customer-activation#63]
Hi. After i install the extension with magento connect manager, i try to view customer managemant and its say : Fatal error: Class 'Netzarbeiter_CustomerActivation_Block_Adminhtml_Widget_Grid_Column_Renderer_Boolean' not found in /var/www/vesttruck.ro/httpdocs/app/code/core/Mage/Core/Model/Layout.php on line 491.

And when i go to Configurastion > Customers > Configure Customers then i get this :
Fatal error: Call to a member function toOptionArray() on a non-object in /var/www/vesttruck.ro/httpdocs/app/code/core/Mage/Adminhtml/Block/System/Config/Form.php on line 463

Would like to get advice because im just a rookie in this domain. Thank you!

**Comment by shankar2004nag** [comment]
I am a newbie to Magento
Currently working on magento 2.3.2
After i execute setup:upgrade
Module is not enabled. Later realised registration.php is not present.
But even after adding registration file it does not work

**Comment by Vinai** [comment]
The module is not compatible with Magento 2.
