### ISSUE TITLE
New Customer Activation Notification Email Not Sending

### ISSUE THREAD

**Issue by supriyoalam** [Vinai/customer-activation#64]
Hi,
I have installed Netzarbeiter_CustomerActivation Version number: 0.5.3 on Magento Community ver. 1.8.1.0, everything working fine including activation except sending confirmation email to customer. Please help.
Thanks,
Alam

**Comment by fakhrin** [comment]
Hi Vinai, 

I am facing the same issue.

User activation is working fine. Administrator is able to activate user from the back-end.

My only problem is there are no emails being send to user and Administrator upon registration. User should be able to receive a notification stating account has been activated while Administrator should be notified upon any user registration.

Thank you.

**Comment by Vinai** [comment]
Thanks for letting me know the solution, that is great to know! Now I can point people to your answer if someone else has the same issue.

**Comment by fakhrin** [comment]
Hi Vinai,

Great to know a great extension too!

Thank you.
