### ISSUE TITLE
REQ: Customer Activation Expiration date option

### ISSUE THREAD

**Issue by bbuds** [Vinai/customer-activation#71]
Please add an expiration date for customer accounts. This way if the account is automatically set to "inactive" after the expiration date.

**Comment by Vinai** [comment]
Thanks for your suggestion. I like the idea, but it will be quite some time until I have enough time to implement it.
Maybe I'll won't even get round to it for Magento 1. At one point I plan to port all my supported extensions to Magento 2. That might be an opportunity to add that feature.
I'll leave this issue open until then.

**Comment by bbuds** [comment]
Cool. Understood--been swamped too lately.
