### ISSUE TITLE
Authorize.net response not allowed

### ISSUE THREAD

**Issue by pwarmen3** [Vinai/customer-activation#73]
Hey Vinai, Thanks for writing this.

Any reason as to why it would prevent the onepage checkout controller from getting a response from Authorize.net? 

I have not looked into the issue myself, instead thought I would ask you here first to see if you already have a fix for it. 

I can provide more information if you require it

Thanks

**Comment by Vinai** [comment]
Hi,

I don't know how this module could cause that behaviour. Maybe you are refering to the [Netzarbeiter_LoginOnlyCatalog](https://github.com/Vinai/loginonlycatalog/) extension?

**Comment by pwarmen3** [comment]
No, I only have this one installed. Certainly could just be specific to my installation, have you had success using this mod with the Authorizenet module?

I thought about adding something like this: 

    protected function _isAuthorizenetRequest()
    {
        return Mage::app()->getRequest()->getModuleName() === 'authorizenet';
    }

and 

        if ($this->_isApiRequest() || $this->_isAuthorizenetRequest()) {
            return;
        }

**Comment by pwarmen3** [comment]
Thanks for your response Vinai, you are probably right I think there is a different module causing this. I can let you know in a moment. Someone installed one without my knowledge

**Comment by pwarmen3** [comment]
Yes most certainly was the other module by Sitewards. It wasn't until you mentioned [Netzarbeiter_LoginOnlyCatalog](https://github.com/Vinai/loginonlycatalog/) that I noticed the other module. Can you tell me if you have tested Authoriznet DPM transactions with [Netzarbeiter_LoginOnlyCatalog](https://github.com/Vinai/loginonlycatalog/)

**Comment by pwarmen3** [comment]
Not to worry, I will test the module myself and simply thank you for the code. I looked at the code and it seems as though it will not interfere with the checkout controller, and it would appear that you have provided method of allowing/disallowing routes. Thanks again

**Comment by Vinai** [comment]
The LoginOnlyCatalog extension can be disabled on specific routes in the system configuration in the admin interface.
The routes to add would be
 ```
authorizenet/directpost_payment/response
authorizenet/directpost_payment/redirect
authorizenet/directpost_payment/place
authorizenet/directpost_payment/returnQuote
```
```

**Comment by pwarmen3** [comment]
thanks! you rock
