### ISSUE TITLE
Call to a member function massSetActivationStatus() on a non-object

### ISSUE THREAD

**Issue by in2computing** [Vinai/customer-activation#81]
Hi

I run Magento 1.9, just installed this extension and receiving below error message. Is your extension compatible with Magento CE 1.9?

Fatal error: Call to a member function massSetActivationStatus() on a non-object in /home/ranksent/public_html/app/code/community/Netzarbeiter/CustomerActivation/sql/customeractivation_setup/mysql4-upgrade-0.2.8-0.2.9.php on line 33

Looking forward to hear from you

Regards
Yogi

**Comment by Vinai** [comment]
Please check the `var/log/exception.log` file. There should be some additional error regarding the class `Netzarbeiter_CustomerActivation_Model_Resource_Customer`.  
Please also check if the file `app/code/community/Netzarbeiter/CustomerActivation/Model/Resource/Customer.php` exists on your system.

This might help narrow down the issue.

**Comment by swbeeton** [comment]
Hi, can confirm the error above in a Magento CE 1.9 installation.

Could not find any reference to Netzarbeiter in the exception log, Customer.php did exist.

Let me know if you'd like more information.

Please note that I *DID NOT* upload composer.json or the modman file to the host. Let me know if this is required and I will retry.

**Comment by Vinai** [comment]
Hi,

The `modman` or `composer.json` files are not required for production, they only assist installation.
I'm not able to reproduce the issue on CE 1.9. The above error the original poster shared means Magento isn't able to instantiate said resource mode.
This can happen for two reasons

1. The class file is missing (or empty)
2. The `etc/config.xml` file containing the class group definition isn't loaded

The first reason you already ruled out. So it has to be the second reason. Please check the file `app/code/community/Netzarbeiter/CustomerActivation/etc/contig.xml` exists and is not empty.

**Comment by in2computing** [comment]
Hi
The issue was with Web-Form CRF extension, reinstalling the extension sorted out the issue.

Thanks for all your suggestions. I really appreciate it.

Regards
Yogi

**Comment by Vinai** [comment]
Thank you for posting an update!
