### ISSUE TITLE
[Not issue - Question] -  how to send notification using script?

### ISSUE THREAD

**Issue by brazzil** [Vinai/customer-activation#83]
To activate the accounts I use the following script and works properly. How I can send the customer notification email using this script? thx

$customers = Mage::getResourceModel('customer/customer_collection')->addAttributeToSelect('*')->addAttributeToFilter('customer_activated', array('neq' => 1));
foreach($customers as $customer)
{
  $customer->load($customer->getId());
  $customer->setCustomerActivated(1);
  $customer->save();
  };

**Comment by Vinai** [comment]
If you load the global events area in the script then it the regular event observer will be triggered and the emails sent automatically.
However, if you prefer you can send the notification email to a customer using
```php
Mage::helper('customeractivation')->sendCustomerNotificationEmail($customer);
```
