### ISSUE TITLE
customer-activation

### ISSUE THREAD

**Issue by girishghodke88** [Vinai/customer-activation#87]
HI Sir,
I installed the extension but it does not send email to strore id and customer.

**Comment by Vinai** [comment]
The system uses the same email sending facilities as all other Magento emails, so the exact setup required depends on the Magento version.

**Comment by girishghodke88** [comment]
Thanks Sir now the extension is working fine.
            we are using this magento platform to develop android app.So can you suggest how I  can  send email to store id when customer request to login form android phone.

**Comment by Vinai** [comment]
Thanks for the update. This kind of help request is out of scope for this issue tracker. Please post a question in the Magento community forum, or at http://magento.stackexchange.com/
