### ISSUE TITLE
Not all options visible in configuration, e-mails not being sent

### ISSUE THREAD

**Issue by ingmardevos** [Vinai/customer-activation#88]
I installed the extension a while ago on magento 1.9.2.1, now we are testing the shop and found out that the activation e-mail isn't being sent to both the admin and user. When I looked in the admin for configuration options I noticed that I only have 2 config options. I already uninstalled and reinstalled without effect. I downloaded the latest version from today.
![screenshot 2015-10-30 12 09 07](https://cloud.githubusercontent.com/assets/15428631/10844432/cb6ae1b4-7eff-11e5-8255-2c1902dfe704.png)

**Comment by Vinai** [comment]
The registration notification is only sent to the admin.
The email on customer activation is only sent to the customer.

There is no option to send the emails to both users.

**Comment by ingmardevos** [comment]
I meant that neither of the e-mails is being sent at all. But if I look at screenshots from other users there is a whole list of options (also in the manual), which I don't have in the backend?

**Comment by ingmardevos** [comment]
Issue was with CloudFlare. Changing the first option in the extension in the config was supposed to show extra fields/options. Because of a JS error this didn't happen. So is resolved now.
