### ISSUE TITLE
Problems Since Supee-6788

### ISSUE THREAD

**Issue by scarrott** [Vinai/customer-activation#91]
We are having problems with the extension since installing this patch. We have upgraded all the Customer-Activation files on here since patching and cleared cache. Customers are registering fine and not being activated by default, but it is now impossible to activate them. In the Manage Customers list if we tick a customer and choose Actions > Customer Activated > Yes then Submit, we get a 404 error page (with the address http://www.darenthmjsspares.com/index.php/admin/customerActivation/massActivation/)

If we click the customer's name to see full details and go to the Account Information tab, the 'Activated' option is not there. 

Any ideas what is happening? I've checked in Config that everything is activated.

**Comment by scarrott** [comment]
We've figured it out. There is an error in the config.xml file. Line 95 needs changing to:

<netzarbeiter_customeractivation after="Mage_Adminhtml">Netzarbeiter_CustomerActivation</netzarbeiter_customeractivation>

Hope this helps others.

**Comment by Vinai** [comment]
Thank you for the update, will push version 0.5.6 with that addition shortly!

**Comment by Vinai** [comment]
Updated to 0.5.6 with the fix from @scarrott

**Comment by navarr** [comment]
Shouldn't this issue be closed, then?

**Comment by Vinai** [comment]
I'd like to have confirmation of one of the posters that the issue really is resolved before closing the ticket.

**Comment by scarrott** [comment]
All working for me since we made that fix, so think it can be closed.

**Comment by Vinai** [comment]
Thanks for the update!
