### ISSUE TITLE
Prices not hidden

### ISSUE THREAD

**Issue by gadgetmanjay** [Vinai/customer-activation#94]
MY stores are B2B and have prices hidden until logged in by authorised customers.

I have Amasty HidePrice extension to do this however there is problem which I have asked Amasty support and they say its this extension that is the fault.

When customer registers they receive the notification to wait till activation;
http://prntscr.com/9te2q3

Users are not getting email confirmation.  Admin isn't getting email confirmation.

If the customer return and tries to log in they receive the message ' this account is not activated';
http://prntscr.com/9te412

BUT.....At the top of the page it says 'Welcome xxxxx (Not xxxxx)..... and shows the account user name.
AND If the user then browses for products they can see the price as though they are logged in.

So it appears as though the extension isn't looking customers out.  It seems as though attempting to log in is creating a valid cookie.

I am on the latest version.

**Comment by Vinai** [comment]
Probably it's a rewrite conflict between the two extension. I don't know the Amasty HidePrice extension, and I can't provide any support for conflicts. I'm afraid you will have to debug and resolve the conflict on your own. Sorry.

**Comment by gadgetmanjay** [comment]
So your not even willing to at least have a look, when the problem is clearly this extension?

**Comment by Vinai** [comment]
In case of conflicts there is no "one" problematic extension, but the problem arises from the combination of two extensions.
That said, if I had time, sure, I'd take a look. But currently I have no time do donate to this extension.
